env:
  browser: true
  es2021: true
root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules: {}
