version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: zemi_webapp_container
    command: npm run dev
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:8080
